### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by stagefright5** [suhay/vscode-editor-group-minimizer#10]
- Ability to add a single editor tab to the named group (using context menu, for example)
- Ability to select the editor tab/s and add selected tabs to a named group
- Add the focused editor group tabs to a new minimized group (Currently, every editor group's tab is added)
- Add the focused editor group tabs to an existing group
- Restore the minimized editor tab group into a new editor group (to right, left, down or up)

I am not sure if all of these are possible with the currently exposed APIs.
Also, there is a feature request to make this part of the vs code itself. You can upvote it so that it can be triaged: https://github.com/microsoft/vscode/issues/109771

**Comment by SergeyBeloglazovRL** [comment]
+1
At least
> - Ability to add a single editor tab to the named group (using context menu, for example)

Additionally

- Ability to remove a single file from minimized group

It makes minimized groups fully editable

**Comment by suhay** [comment]
I was able to implement some of these features, but others are a touch impossible with what we have available right now.

I was able to add a context menu to individual tabs and allow you to select already minimized groups to receive the editor. In the current form, I'm leaving the tab open instead of closing it like the full minimize behavior does. I felt this would be the more useful use case based upon testing, but we can discuss other approaches if it's confusing.

You can also now remove editor documents from a minimized group's list directly from the tree view. Once all documents are removed, the editor group will self destruct just to keep the list view clean. I was not able to target panes in this go around. I'll need to play around with a couple of things to see if that's possible, but we may need to wait for additional features from the API. I'll open another issue to bring the roaming requests, and a bug ticket, together to keep track of this.

**Comment by SergeyBeloglazovRL** [comment]
Thank You!
